### ISSUE TITLE
CycleGAN uses all default hyperparameters?

### ISSUE THREAD

**Issue by Embeddave** [Panda-Peter/visda2019-multisource#1]
Hi @Panda-Peter thank you for sharing this code and your group's great approach to the VisDA challenge

I'm trying to determine what hyperparameters you all used for training CycleGAN.
From the [text file you shared](https://github.com/Panda-Peter/visda2019-multisource/blob/master/dataset/cyclegan_param.txt) it looks like those are all the defaults?

Can you please confirm whether this is correct?
Just trying to make sure we understand your approach

**Comment by Panda-Peter** [comment]
> Hi @Panda-Peter thank you for sharing this code and your group's great approach to the VisDA challenge
> 
> I'm trying to determine what hyperparameters you all used for training CycleGAN.
> From the [text file you shared](https://github.com/Panda-Peter/visda2019-multisource/blob/master/dataset/cyclegan_param.txt) it looks like those are all the defaults?
> 
> Can you please confirm whether this is correct?
> Just trying to make sure we understand your approach

**Comment by Panda-Peter** [comment]
> Hi @Panda-Peter thank you for sharing this code and your group's great approach to the VisDA challenge
> 
> I'm trying to determine what hyperparameters you all used for training CycleGAN.
> From the [text file you shared](https://github.com/Panda-Peter/visda2019-multisource/blob/master/dataset/cyclegan_param.txt) it looks like those are all the defaults?
> 
> Can you please confirm whether this is correct?
> Just trying to make sure we understand your approach

Yes. All the hyperparameters are default.

**Comment by Embeddave** [comment]
Thank you!

I know there's different ways of reporting these things, and the .txt file got me most of the way there. Just wanted to confirm.

The technical report has definitely informed our thinking, we'll be sure to cite it.
Very much appreciate your sharing, especially trained models + results.
